### ISSUE TITLE
tkinter error with docker install

### ISSUE THREAD

**Issue by dprotter** [justinblaber/multi_pyspin#1]
Hi! I built this project by cloning it and building from the docker dockfile (on a mac, although the point of docker is that it shouldnt matter, right???). The build seemed to go fine, but when I tried to launch it I got:
`_tkinter.TclError: no display name and no $DISPLAY environment variable`

Any idea what I've screwed up?
Thanks!

**Comment by justinblaber** [comment]
The docker needs access to your x server. Have you tried using the singularity container? You don't need to build anything. Just download it and run it (after installing singularity: https://github.com/sylabs/singularity

If you want to use docker, you can try something like this: http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/ 

Or you can install ssh inside the container and ssh it to with the "-X" option. I'd highly suggest just using singularity though.

**Comment by dprotter** [comment]
Hi, thanks for the advice. I eventually got the docker container running (although I took bad notes and am having trouble replicating what I did last time, haha), but I had a free afternoon and decided to try the Singularity container you recommended. (Again, I'm on a mac, so I had to install singularity in a vagrant virtual box) I ended up getting the exact same tkinter error, which was interesting. Any thoughts?

Thanks!

**Comment by dprotter** [comment]
I actually eventually got it working (only took 43 min!) using a variety of x11 forwarding tactics. I dont fully know what I'm doing, but inside the vagrant box I installed xauth, x11-apps, and added "X11UseLocalhost no" to the /etc/ssh/sshd_config file. I also modified the Vagrantfile with "config.ssh.forward_x11 = true" and now I get a nice pyspin GUI. Yay!
